apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: aspnet
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: aspnet
     template:
       metadata:
         labels:
           app: aspnet
       spec:
         containers:
         - name: aspnet
           image: aspnet
           ports:
           - containerPort: 80